### ISSUE TITLE
Multiple Publication support?

### ISSUE THREAD

**Issue by andrewvmail** [bakerframework/bakercloud-ce-console#10]
Does this support multiple publications? example outputting 2 different shelf.json depending on which app makes the call?

Thanks in advance!

**Comment by nin9creative** [comment]
Yes

**Comment by andrewvmail** [comment]
Oh thats great! Will probably replace my older server with this then.
Thanks for the quick reply!

**Comment by nin9creative** [comment]
Sure, no problem.

**Comment by nin9creative** [comment]
Hopefully this can be closed?  Reopen if necessary!
