### ISSUE TITLE
Problem with the index.php file.

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/bakercloud-ce-console#13]
I am currently following the magrocket steps of implementing the server api and app needed to do auto renewable subscriptions. I have made two subdomains, one for the api, and one for the app. When i go to he app subdomain it reads this 
Fatal error: Class 'MY_Input' not found in /hermes/bosoraweb021/b1177/ipg.livrepressnet/app/system/core/Common.php on line 174

But when i go to the api subdomain it gives me the magrocket api welcome page. I am not sure what is wrong.
Thanks in advance,
Travis

**Comment by nin9creative** [comment]
What host are you using?

Regards,
Andrew

**Comment by codegeek511** [comment]
I am using iPage.com

**Comment by nin9creative** [comment]
Is that a shared host or VPS?

**Comment by nin9creative** [comment]
The Administration Console side uses a framework called CodeIgniter.  I'm not sure specifically of the setup of the Linux environment at iPage.

**Comment by codegeek511** [comment]
I believe it is a shared host.

**Comment by codegeek511** [comment]
I will have to check with them to see if they supportLinux environments like that. But is it possible that the api will work but the app will not?

**Comment by nin9creative** [comment]
They might have something disabled that the CodeIgniter Framework (used for the app) requires.  Not totally sure just form that one error.

**Comment by codegeek511** [comment]
What are the server requirements, so i can ask them?

**Comment by codegeek511** [comment]
So I talked to the guys at iPage, and they had one of the technical specialist guys help us. He said this :

"The issue appears to be with script. I have uploaded a test script at http://livrepressnet.ipage.com/app/info.php and it is loading fine. I request you to validate the script from your end."

So I am not complete sure what I can do now. I would like to avoid switching to a new hosting company, but if that is the only way to fix it than i guess thats what i have to do.

**Comment by nin9creative** [comment]
Well lots of people have this installed and running with no problems.  Doesn't sound like your host is being very helpful!<a href="http://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>

**Comment by codegeek511** [comment]
SO i checked again with them, the code igniter is not supported. I don't suppose there is a way around this? If not is there solution you have for hosting? I went to wired tree and known host, but those are a bit pricy for my company right now.

**Comment by nin9creative** [comment]
Digital Ocean http://bit.ly/1aivj1E

Regards,
Andrew

**Comment by MaverickWar** [comment]
Try chkhosting.com great hosting provider, never had any real issues and support is spot on. If there was something I needed supported on the server. I just asked and they did their best.

Try them

**Comment by MaverickWar** [comment]
Also I have successfully hosted magrocket with them for myself and a client. Non issues.

**Comment by MaverickWar** [comment]
http://www.chkhosting.com is the link

**Comment by codegeek511** [comment]
I have signed up with digital ocean, but what image should i make my virtual server be?

**Comment by nin9creative** [comment]
Look at this thread.

https://github.com/bakerframework/bakercloud-ce-console/issues/11
