### ISSUE TITLE
BakeAdmin password?

### ISSUE THREAD

**Issue by t0rn** [bakerframework/bakercloud-ce-console#14]
I would like to add users. So i need an administrator's username and password. For magrocket by default it was MagRocketAdmin with password: M@gRocket.
what password  is for BakerAdmin?
Thx!

**Comment by nin9creative** [comment]
BakerAdmin
B@ker

**Comment by t0rn** [comment]
thank you!
Files located at www.bakercontent.com not found.
example http://www.bakercontent.com/publication/com.nin9creative.baker/samplemagazine.hpub

**Comment by nin9creative** [comment]
Sorry, should be fixed now...  Something was wrong on my end.
