### ISSUE TITLE
how do i remove image validation when adding user ?

### ISSUE THREAD

**Issue by axilaris** [bakerframework/bakercloud-ce-console#15]
Hi,

I have a requirement, that i need to remove the image validation when adding a new user ? how do i do that ?

https://github.com/bakerframework/bakercloud-ce-console/blob/master/source/application/third_party/scrud/templates/template_functions.php

how to remove this and not require to validate at all ?
"btn" value="Choose..."

Thanks.
Ax

**Comment by nin9creative** [comment]
What are you trying to do?

**Comment by nin9creative** [comment]
Is this still an open item, if not please go ahead and close this issue.
