### ISSUE TITLE
Does this also work for standalone iOS applications?

### ISSUE THREAD

**Issue by DannyMurphy** [bakerframework/bakercloud-ce-console#16]
Does the backend system/api also manage publications/issues for Baker apps which have been built as standalone apps?

Thanks,
Danny

**Comment by nin9creative** [comment]
No.  Not currently.

**Comment by DannyMurphy** [comment]
Thank you @nin9creative. 

Do you think there would be a lot of work reworking the backend to manage the issue for a standalone app? We are looking current at offering all issues as free (no in-app purchase) but using this to house and serve downloads for the app.

D

**Comment by nin9creative** [comment]
You could do that with the newsstand mode and have just a free subscription and free issues.  They don't have to be paid!

Regards,
Andrew

**Comment by DannyMurphy** [comment]
Thanks
