### ISSUE TITLE
System Log Problem

### ISSUE THREAD

**Issue by webcarp** [bakerframework/bakercloud-ce-console#17]
Hello. 
I am Gabi and have just published a magazine in the appstore with Baker Framework: CarpMAG
Congratulations for your work. It is incredible!
I have a problem: The system log manager not show new logs from the day 29/1/2014 … and the magazine is active! There are new purchases and subscriptions!
Thank you very much for the help

**Comment by nin9creative** [comment]
What is the development mode set to ?

Regards,
Andrew

**Comment by webcarp** [comment]
Thank you very much for answering.
![captura de pantalla 2014-02-01 a la s 16 36 18](https://f.cloud.github.com/assets/6560159/2057950/c5cb6556-8b56-11e3-8beb-e18a659e8b73.png)

**Comment by nin9creative** [comment]
The development mode affects the logging level.  Otherwise the api only logs errors and warnings.  Not Info statements...

Regards,
Andrew

**Comment by webcarp** [comment]
Ok. I understand then that now that the magazine is in production, in the logs only the problems will go out.
I am going to start another magazine … therefore it will have a time of " development mode true ". Then there will go out the information of both magazines in the logs? Or only of the new magazine?

**Comment by nin9creative** [comment]
Just the magazine that you have the development mode turned on for.  The API knows which publication is being accessed and checks the flag.

Andrew
