### ISSUE TITLE
My paid issues are saying updating price, but don't ever actually show the price.

### ISSUE THREAD

**Issue by codegeek511** [bakerframework/bakercloud-ce-console#18]
I am in the middle of migrating from one server to another. I had my issues on this server, and have moved them to my new server. I updated my app in Xcode, but when i test it the paid issues constantly say updating price. The free ones work fine, and all the pics and metadata appear. What is wrong with what i did?

**Comment by nin9creative** [comment]
Check that the Product ID's are correct.  Check the API result for the issues and make sure they match what you defined in iTunes Connect.

**Comment by codegeek511** [comment]
The Product ID's are the same, but what do you mean about the API result? I don't understand what your asking me to check.

**Comment by codegeek511** [comment]
Also, my paid subscriptions aren't showing up. The free one does. The Product ID's for that is also correct.

**Comment by nin9creative** [comment]
Are the paid subscriptions defined in constants.h?<br/><br/>You are testing on an actual device correct?<a href="http://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>

**Comment by codegeek511** [comment]
yes they are defined in there. No not on an actual device, on the ipad simulator. I can try on a real device though.

**Comment by nin9creative** [comment]
For ios7 you need to test on a device.

Regards,
Andrew

**Comment by codegeek511** [comment]
wow....missed that. Ok, well its all fixed now. Hahahaha thanks!

**Comment by nin9creative** [comment]
With 7.0 the simulator can't be used to test IAP.  Not sure if 7.1 will fix that or not, I haven't had a chance to test.<a href="https://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>
