### ISSUE TITLE
Upgrading doubt

### ISSUE THREAD

**Issue by fobetor** [bakerframework/bakercloud-ce-console#2]
Hello andrew
 I have the magrocket version installed (1.0 i think, the one from magrocket.com, 20 days ago)
 I imagine it is convenient to upgrade to CE version.... But my app is prepared for the previous one... To upgrade... I just overwrtie all files in the server maintaining the config ones? Or i need to make other changes that affects my app store binary?
Thank you

**Comment by nin9creative** [comment]
Unfortunately at this time there is no way to "upgrade' from MagRocket 1.0 to this one automatically.

I will try to see if I have time this week to write instructions on how to do an upgrade from one version to another.
The file side would be pretty straightforward - however the DB structure changed a little bit too.

**Comment by fobetor** [comment]
So.... it's better to install the CE version before I starting everything in production? Does it change the calls inside the Baker app or they are the same as in magrocket so I dont need to re-submit it to app store?
Thank you

**Comment by nin9creative** [comment]
If you have not yet moved to production - you may want to install the CE version.

Nothing should change inside the Baker app if you install the CE version at the same location.  The endpoints for the API won't change.

Andrew

**Comment by fobetor** [comment]
Ok.. I will start a new installation....The instructions are the same as for magrocket ?

fernando

**Comment by nin9creative** [comment]
Should be the same.

Andrew
