### ISSUE TITLE
Allow readers who subscribed before we started using BakerCloud access? 

### ISSUE THREAD

**Issue by theBrandonWu** [bakerframework/bakercloud-ce-console#21]
We have been using Baker for the app for a few months now without a server back-end — all issues have been free so far and we've just set up a server with BakerCloud to start looking into paid issues. However there are readers who have subscribed to the magazine via IAP before we set up our BakerCloud server. How can we set it up so that these readers will have access to issues once we push this live with a new app update? (Our goal is for subscribers to have access to all issues regardless of when they start subscribing.)

Thanks!!

**Comment by nin9creative** [comment]
Hmmm, so you are going from free to paid subscriptions?  Or will it still be free?

**Comment by theBrandonWu** [comment]
Thanks for the quick reply! The magazine was always a paid magazine but when we switched to Baker we made all issue free until we get the back-end set up. So free to paid subscriptions — and we want to make sure people who have paid for subscriptions can get the issues without having to pay again.

**Comment by nin9creative** [comment]
I see...  Well, it won't be a totally smooth transition as by default Baker and the backend won't know about the prior purchases.  However if you ensure that your app id on the Baker side as well as the in app purchase product ids that were used in the prior app match, then it may be just that the users need to restore their purchases.

Is that possible?  Did the prior paid app get released under your developer account?

**Comment by theBrandonWu** [comment]
Ah good point re: restoring purchases. Yes the app id and iap product ids are the same, so is the developer account. How will that work internally when an user restores a purchase. If the user id is not found on BakerCloud, will it create one in the Subscriptions log and grant access?

**Comment by theBrandonWu** [comment]
Just a quick update. Restoring purchase and then a refresh seems to do the trick (in sandbox mode). Thanks! :+1:
