### ISSUE TITLE
Tokens explanaition

### ISSUE THREAD

**Issue by fobetor** [bakerframework/bakercloud-ce-console#24]
Hello,
 I'm a little bit lost about tokens. 
The point is that, if itunnes connect tellls me that i have i.e: 1000 app downloads... Why in cloud CE console i have only i.e:400 tokens listed?
 Its a free issues app, but I think i am missing something I dont have or understand the idea.
- Is it that Baker Cloud only registers tokens for the users that download at leat one issue?
  -Or only when a user executes at least once the app?
  
  Or.. Is baker registrering incorrectly the new downloaded app?

In any of the above cases... Is there a way to know the tokens? (Itunnes connect, ....)
I dont have clear if baker just registers the tokens for downloaded issues or for the app.
Thanks in advance

**Comment by nin9creative** [comment]
Only if someone selects "yes" to the push notification prompt....

Regards,
Andrew

**Comment by fobetor** [comment]
Thank you Andrew. 
Now its clear.
