### ISSUE TITLE
itunes ATOM feed API error, variable user_id undefined

### ISSUE THREAD

**Issue by afurnas** [bakerframework/bakercloud-ce-console#26]
The ATOM feed crashes because line 449 in index.php references $user_id on the call to logAnalyticMetric function. Unfortunately, unlike most of the api calls, the ATOM feed does not pass user id and therefore the call crashes at this point.

I resolved locally by replacing $user_id with a blank string on the call to logAnalyticMetric

![screen shot 2014-02-28 at 1 13 33 pm](https://f.cloud.github.com/assets/781392/2296906/208d3eca-a0a5-11e3-8731-fc01eb7d42fe.png)

**Comment by nin9creative** [comment]
Ah, that one slipped through the cracks...

**Comment by afurnas** [comment]
The quality of the application is so high that I was pretty sure I had configured something incorrectly. :)  Thank you for a great app.

**Comment by nin9creative** [comment]
Yeah, must not have tested that bit after adding in some additional analytics changes!

Andrew

**Comment by nin9creative** [comment]
Just pushed a fix for this error in bakercloud-ce-api Master

https://github.com/bakerframework/bakercloud-ce-api/commit/d037d58e4c4431a44adf08bc4ba2bb968724f5ba
