### ISSUE TITLE
Issues with MagRocket Installation

### ISSUE THREAD

**Issue by tomibady** [bakerframework/bakercloud-ce-console#28]
Please kindly assist me with the installation of Magrocket, the reply I got after uploading the files to my server was 

Unable to connect to your database server using the provided settings.
Filename: core/Loader.php
Line Number: 346

Please kindly advise on how to go through this, you assistance is very much appreciated.

**Comment by nin9creative** [comment]
No longer support MagRocket - do you mean Baker Cloud CE?

Andrew

**Comment by tomibady** [comment]
Yes please Andrews, I mean the Baker Cloud CE

**Comment by tomibady** [comment]
And help on this, I'm using Godaddy Dedicated IP Host for the deployment, please kindly advise.
 Thanks.

**Comment by lumierephoto** [comment]
In the database.php file you need to change the value in this line to false:

```
 $db['default']['db_debug'] = FALSE;
```

**Comment by tomibady** [comment]
Thanks very much @lumierephoto, I tried it but it didn't work.
