### ISSUE TITLE
Give free a paid Subscription

### ISSUE THREAD

**Issue by crisgarner** [bakerframework/bakercloud-ce-console#30]
Is there a way to give free a paid subscription to a user?, like a gift.

I guess I have to insert manually a purchase and receipt, but seems like I need to get the User Id someway

**Comment by nin9creative** [comment]
Right now you can't really add a subscription as a gift, as the /PURCHASES api endpoint checks for receipts and whatnot and
will not recognize the user as subscribed.

You can add individual issues to the purchases table and it should work if you know the user_id.

At some point in the future there will be an enhancement for this type of thing.

Andrew

**Comment by crisgarner** [comment]
@nin9creative Thanks for the response, I guess ill give free issues then, You know how can I get the user_id?, so I can ask the users to send it to me.

**Comment by nin9creative** [comment]
Well, that's another bit that's tough right now.  For another project I implemented, I added the IP Address as part of the system logging.  That's not currently
something in the CE version.  Then I would just ask the user to send me their IP that they currently are connected with after using the app.  Then you can
correlate the IP address with the user id in the system log table.  

Kind of a pain.

**Comment by crisgarner** [comment]
Yeah, sounds like it is a pain, I'll see if I can implement a logging with email, so that way besides checking for purchases it checks for the logged user.

**Comment by pattypatpat** [comment]
I came here with a similar issue, good to know I can add issues to the purchase table and provide free issues. 

I use this website to request UDIDs, it's pretty easy to follow and works with our customers so it may be a good work around till there is another way to add subscriptions: http://whatsmyudid.com/

**Comment by nin9creative** [comment]
I'm hoping that at some point we'll support an easy way of doing this through the Baker Cloud Console, with some sort of
login or code redemption within the Baker UI.

**Comment by pattypatpat** [comment]
Hi Andrew,

No worries at all. I do have a question for you though. I tried to offer a free issue via the purchase tables, and it doesn't seem to be working for me. The steps I took below, if you can pinpoint if I've missed anything:
1. Obtained UDID from customer.
2. Added a Purchase item for an individual issue (included App ID, User ID, Product ID). I noticed the UDIDs on Baker had dashes in certain places so I replicated this on the UDID I added).
3. Tested the magazine app for this newly added UDID record, including 'Restoring purchases' but no response in terms of the issue converting to 'Purchased'.

Appreciate the help, thanks.
Pat

**Comment by nin9creative** [comment]
The problem is that I don't know what UDID you are getting.  Baker generates its own unique id on each
install of the app...  That is the ID you'll need.

In a production app for a client, I put in IP Address logging in the API so that it tracks IP addresses in the System Log.
I ask the user for their IP, then look up their USER ID with the IP address and then use that ID.

It's a total workaround, but does work.

You need to ensure you are getting the correct value.

Andrew

**Comment by pattypatpat** [comment]
Ah ok, I didn't know Baker generated its own unique ID. I'll try what you've said above, can I ask how you look up the USER ID using the IP?

Thanks for your help, mate!

**Comment by pattypatpat** [comment]
Sorry, I just re-read your response. I don't think I have IP address logging in the API as my System Log doesn't record them. Not sure how best to proceed from here as without an IP record I can't see the corresponding User ID. Any way forward?
