### ISSUE TITLE
Installed BakerCE, but can't login

### ISSUE THREAD

**Issue by lumierephoto** [bakerframework/bakercloud-ce-console#31]
I've successfully installed the bakercloud-ce-console here:

http://app.fillesmag.com

However, I'm unable to login with the given credentials:

user
123456

Ever run into this issue?

**Comment by tomibady** [comment]
Hi, I tried checking your api db connectivity just now and I got the result below:

{"BakerCloud API":{"Error":"SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"}}

I think you should check your database connection details in the api index file.

**Comment by nin9creative** [comment]
It's a database connection error.  Is PDO for MySQL enabled on your hosting account?

Andrew

**Comment by nin9creative** [comment]
Check the actual database table for the users, did the sample data get installed?

Andrew

**Comment by lumierephoto** [comment]
I never figured out how to fix this on my shared server, but I'm pretty sure it was because I had:

```
 $db['default']['hostname'] = 'localhost';
```

Get in touch with your host to find out what you should put down as your hostname. Also, PDO may need to be enabled as it states in the comments of the database.php file.

The good news, is that I got it working on a Digital Ocean droplet using VirtualMin as the control panel!

**Comment by nin9creative** [comment]
That's true @lumierephoto - a lot of shared hosts have a different setting for the MySQL hostname.

Digital Ocean is a great offering and perfect for Baker Cloud CE!

Andrew
