### ISSUE TITLE
Questions about APNS Token

### ISSUE THREAD

**Issue by fiurdy** [bakerframework/bakercloud-ce-console#32]
On BakerCloud under the top menu Data Browser > APNS Tokens, I can only see ONE APNS Token while my app is tested on several other devices with notification being enabled.

1) Why doesn't it register my other devices?

2) Tested the push notification, it works (but of course, only for that particular APNS Token that belongs to a single device)

3) Data Browser > System Log is actively logging "Storing APNS Token for APP ID:" but the token is not stated there.

Is this a normal behaviour for Development and will I see more tokens during Production?

Lastly, is it possible to send Push Notification during Production from my mac, without needing a sever? (I'm able to send it using a Development certificate. Safe to assume it will work with Production certificate?)

**Comment by nin9creative** [comment]
1)  It should only show up if you click on the allow push notification prompt when Baker runs the first time after being installed.  If you do that and your certificate is provisioned for push notifications, the token should be logged in the backend.

2)  Is there a question here?

3)  Odd, it should work if 1) is correct above 

Development should match the behavior of Production.

You'll need something like Parse.com, Urban Airship, or my favorite Amazon SNS (works perfectly well with just the tokens stored in the Baker Cloud CE)

**Comment by fiurdy** [comment]
Thanks Andrew.

I think there's a bug in the system, it doesn't store more than 1 APNS token when submitting to #define POST_APNS_TOKEN_URL @"http://api.yourdomain.com/apns/:app_id/:user_id"

Parse works wonderfully, it captures all the APNS tokens of all my test devices.

I'm using the latest commit of BAKER Cloud CE btw.

**Comment by fiurdy** [comment]
Attaching screenshot for reference.

Baker Cloud CE only captures 1 APNS token per one app. The first device.

If the app is installed in more test devices, it doesn't capture the 2nd, 3rd... only the first.

Parse however, captures all APNS tokens from all test devices. Which is odd, right?

![untitled-1](https://cloud.githubusercontent.com/assets/2278328/2622503/2eb1aa64-bcb5-11e3-9de9-f7b9f29f46da.jpg)

**Comment by nin9creative** [comment]
Do you have the constants.h setting set up correctly?

What is the string you have in the file for the APNS API endpoint.

Andrew

**Comment by fiurdy** [comment]
Do you have the constants.h setting set up correctly?

Yes. To triple confirm, i just set up a new app from freshly downloaded Baker Xcode files, set up new IDs on Apple Developer, iTunes connect & Baker CE and ran it on multiple devices.

The first device running the app will get its APNS token stored on Baker Cloud CE. The 2nd and 3rd devices, not appearing.

Comparing the string from the output in Xcode console that prints out "NSLog(@"[AppDelegate] My token (as NSString) is: %@", apnsToken);" confirms i set up the constants.h correctly -- Baker Cloud CE registers the same exact string.

Attached is the latest screenshot. Only one device. While Parse.com registers all test devices with different APNS Tokens.

![untitled2](https://cloud.githubusercontent.com/assets/2278328/2623409/ca465470-bcec-11e3-86f9-48985fcf283a.jpg)

**Comment by nin9creative** [comment]
What is recorded in the system log table?  It should record info related to the token api call.<br/><br/>Andrew<a href="https://overview.mail.yahoo.com?.src=iOS"><br/><br/>Sent from Yahoo Mail for iPhone</a>

**Comment by fiurdy** [comment]
Just the USER ID, like how i mentioned on the first post (3) above, without the token.

Odd?
