### ISSUE TITLE
Help with determining endpoints

### ISSUE THREAD

**Issue by drexxel** [bakerframework/bakercloud-ce-console#33]
I have a couple questions. Ok here's where I'm stuck...

The hpub and cover art are in my Amazon s3 bucket and I know that URL. So I had originally replaced the sample newsstand manifest URL with "http://myurl.com/shelf.json" But then in the installation screencast (and also in the Baker Setup Documentation) it showed this:

 #define NEWSSTAND_MANIFEST_URL @"http://api.yourdomain.com/issues/:app_id/:user_id"

First Question: The :app_id and :user_id part of that sample URL do not exist in my version of Xcode, so do I need to add those to the end of the url? 

Second Question: How do I determine the other endpoint URLs? Just replace the sample domain with my amazon S3 url? I imagine this sounds like a really dumb question, but I'm an artist, not a programmer, I'm honestly amazed I've gotten this far. I guess I'm just determined. :) Thanks SO much in advance for your help.

**Comment by fiurdy** [comment]
hey @drexxel

Baker works with or without Baker Cloud Console.

For those who don't use Baker Cloud Console, they simply point the newsstand manifest URL to where the json file is e.g. http://example.com/shelf.json. They can also choose to add :app_id/:user_id should they need to track unique users with their own system (not Baker Cloud Console)

For those who use Baker Cloud Console, it's mandatory we point it to http://api.yourdomain.com/issues/:app_id/:user_id

The :app_id/:user_id are means to track unique users. Baker Cloud Console uses them to store the strings generated when the app is run.

First Question: Yes if you use Baker Cloud Console, it's mandatory to add :app_id/:user_id.

Second Question: Yes. Just replace the sample domain with your amazon S3 url.

**Comment by drexxel** [comment]
Thank you @fiurdy! I did actually get it figured out. My first app is currently "Waiting for Review"! I couldn't be more excited!!!
