### ISSUE TITLE
API Check DB Connectivity gives 404 Not Found

### ISSUE THREAD

**Issue by ausiuming** [bakerframework/bakercloud-ce-console#34]
I installed ce-console and ce-api in two folders of the same site, in a linux server with php 5.3.24. Ce-console works fine, can add publications and issues. But ce-api gives "404 Not Found error" when clicking the "Check DB Connectivity" button.

**Comment by fiurdy** [comment]
Check your db configuration settings on bakercloud-ce-api/index.php again.

Some webhosts require "localhost" to be the exact URL to where the MySQL database is.

**Comment by ausiuming** [comment]
I renamed the htaccess.txt to .htaccess as told in the htaccess_README WHEN INSTALLING.txt file. Then it works.
