### ISSUE TITLE
Message: unserialize()

### ISSUE THREAD

**Issue by iCandyLabs** [bakerframework/bakercloud-ce-console#35]
I have installed the framework on my LAMP stack and it seems to be working nicely, aside from this error message that appears on all pages except my main dashboard. Here is the full error displayed, I'm using php 5.4.25:

A PHP Error was encountered
Severity: Notice
Message: unserialize(): Error at offset 0 of 5100 bytes
Filename: admin/scrud.php
Line Number: 29

Line 29: $conf = unserialize($content);

**Comment by nin9creative** [comment]
Haven't seen that error before.  It may be something with the PHP version...  Will need to investigate.

**Comment by iCandyLabs** [comment]
I have solved this issue by changing first term of str_replace() from "<?php exit; ?>\n" to:

 "<?php exit; ?>\r\n"

Before:
Line 28: $content = str_replace("<?php exit; ?>\n", "", file_get_contents(**DATABASE_CONFIG_PATH** . '/' . $this->db->database . '/' . $this->input->get('table') . '.php'));

After:
Line 28: $content = str_replace("<?php exit; ?>\r\n", "", file_get_contents(**DATABASE_CONFIG_PATH** . '/' . $this->db->database . '/' . $this->input->get('table') . '.php'));
