### ISSUE TITLE
Cannot Access API

### ISSUE THREAD

**Issue by kukusumaa** [bakerframework/bakercloud-ce-console#36]
I have practice all of step to install Baker Cloud Console (CE) REST API. But when i access "http://api.mydomain.com", i couldnt see the any display of webpage. 
And when i type "http://api.mydomain.com/issues/com.nin9creative.baker/B7340733-CC87-420B-888A-EA24776E276A", i couldnt see anything. Just :
[]
did i miss something?

**Comment by nin9creative** [comment]
Closing due to age of issue.
