### ISSUE TITLE
You've already purchased this In-App Purchase but it hasn't been downloaded.

### ISSUE THREAD

**Issue by ausiuming** [bakerframework/bakercloud-ce-console#38]
Before I set up BakerCloud Console, I can purchase and download issues by the newsstand app in the Sandbox Environment.

Then I set up the BakerCloud Console and API, input publication and issues information, have "Database Connection Test Successful" and made changes in the Xcode project. 

cURL support    is enabled.

But when I purchase an item, I always get "You've already purchased this In-App Purchase but it hasn't been downloaded. [Environment: Sandbox]". It still shows the purchase button instead of the download button.

**Comment by nin9creative** [comment]
Try using a new itunes connect test user ID

Andrew

**Comment by ausiuming** [comment]
I have created some more testing accounts but got similar errors, the error pattern is generally as follows:

When purchase an item or subscription, the app asked for Apple ID and password to proceed purchase. Then pop up:
"Could not confirm purchase with remote server"
"The operation will be retried until it is successful"
for one to several times.

Sometimes but not always, follow by this:
"Purchase failure"
"Cannot connect to iTunes Store"

When purchase the same item again, will give this:
"You've already purchased this In-App Purchase but it hasn't been downloaded."
"[Environment: Sandbox]"

When doing the same subscription again, will give the success message, but will display "you are not subscribed", and still can subscribe again.

The setup of Bakercloud and API seems fine: http://daniel-au.pro/api/issues/com.medcom.yiyaoren/B7340733-CC87-420B-888A-EA24776E276A

I will keep re-examing the documents, the Xcode project, Bakercloud and iTunes Connect settings to see if there is anything wrong.

Any idea on what could go wrong is welcome.

**Comment by ausiuming** [comment]
Sorry missed one important point: no receipt, purchase and subscription record is ever received when I check Data Browser in Bakercloud console.

But there are records in System Log: Checking purchase, retrieving issues, etc.

**Comment by nin9creative** [comment]
Are you testing on an actual iPad device?

Andrew

**Comment by nin9creative** [comment]
Are you using the released version of the API/Console or the GitHub master?

Andrew

**Comment by ausiuming** [comment]
The API/Console is v1.1, Baker is v4.2.1 downloaded from GitHub master.
I'm testing on an iPod Touch/iOS6 and an iPad Mini/iOS7.

**Comment by ausiuming** [comment]
I have read your article "Baker Cloud Console CE - Web Hosting Recommendations" and suspect that the problem is due to my shared hosting plan (http://daniel-au.pro/info.php : Linux, Apache, MySQL, > PHP 5.3, cURL enabled). Seems the communication between iTunes Connect and Baker Cloud is blocked.

I am checking with the hosting company, but they require more information on the server requirement of Baker Cloud, such as whether ports other that 80 are used.

**Comment by ausiuming** [comment]
The company I am working for is going to subscribe a new hosting plan that meets the requirements of Baker Cloud Console CE. Other than VPS, the service provider also has a new Cloud Servers Plan (powered by Parallels Cloud Server). Is cloud servers suitable for Baker Cloud Console CE ? Or is it safer to go for VPS ?

VPS plan: http://www.pachosting.hk/en/server-solution/virtual-private-server-vps.php
Cloud Servers plan: http://www.pachosting.hk/en/server-solution/cloud-servers.php

**Comment by nin9creative** [comment]
I generally just say VPS vs more locked down shared hosting plans.  If it's a scalable cloud server option - that probably is fine...

What I'm typically recommending against is the cheap plans like godaddy or the like - seems like many have had all sorts of issues with those.

Andrew

**Comment by ausiuming** [comment]
I've set up everything in the cloud server but still got exactly the same problem. I've also asked Apple through iTunes Connect Resolution Center. They asked me to read Technical Note TN2259(https://developer.apple.com/library/ios/technotes/tn2259/_index.html). In point 15 it states that :
"What url should I use to verify my receipt ?
Use the sandbox URL https://sandbox.itunes.apple.com/verifyReceipt while testing your application in the sandbox and while your application is in review.
Use the production URL https://buy.itunes.apple.com/verifyReceipt once your application is live in the App Store."

Can I incorporate this in the Baker Xcode project to check if there is any problem in verifying receipt? How to do that?

**Comment by ausiuming** [comment]
I have traced and placed additional logMessage() in the api index.php. Seems an empty  $base64_latest_receipt is retrieved from https://sandbox.itunes.apple.com/verifyReceipt .
I've found in http://stackoverflow.com/questions/11522069/in-app-purchase-sandbox-receipt-validation-fails-because-of-curl-ssl mentioned that a SSL Certificate is necessary. But cURL is enabled and SSL is on in the server. When my colleague checked in Parallels Panel, there is only a default Certificate. No CA Certificate (need to purchase separately). Is an addition SSL Certificate (CA, EV, don't know the differences) necessary ?

**Comment by kukusumaa** [comment]
hi @ausiuming, i have the same problem with you. Do you have fix it?
When the user buy the issue, the problem is [ERROR] Failed POST request to http://api.xx.com/confirm_purchase/:app_id/:user_id: response was 404 not found

**Comment by nin9creative** [comment]
Either the URL is wrong or something is misconfigured with Baker Cloud CE.

**Comment by omegah3** [comment]
@nin9creative I am having  the same problem as above.
What do you suggest as a solution to this problem?
