### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by dettlee** [bakerframework/bakercloud-ce-console#41]
Hi, i m getting stuck on a very beginning, INSTALL
after copy the CONTENT of source to 
http://app.mydomain.com/ 
and navigate to the install. it return a BLANK page ( checked the error return is 404.shtml )
did anyone experience this? can help
thank you. running:
PHP 5.4.29
mysql 5.5.36-cll

**Comment by fcontreras** [comment]
You have to make sure you are using a valid domain that is pointing to your app installation.

**Comment by dettlee** [comment]
yes, domain is up and running. but just getting empty white page. 
tq

**Comment by fcontreras** [comment]
Did you try looking at the PHP error logs... anything to share there?

**Comment by dettlee** [comment]
yes but error log show only 404
[Wed Jul 09 13:24:57 2014] [error] [client 120.151.xx.xx] File does not exist: /home/xxxx/public_html/app.xxxx.com/404.shtml

on the other installation on api there 
Catchable fatal error: Argument 1 passed to Pimple::share() must be an instance of Closure, unknown given, called in /home/xxx

i had tried on different domain.com as well 
tq

**Comment by dettlee** [comment]
thanks for the help. 
i had manage to install on one of the vps, after rebuilding the php. 
but unsuccessful on the other one. will update here. tq

edit.. 
for white screen(baker cloud ce ): rebuild with mysqli module do the trick 
for Catchable fatal error: Argument 1 passed ( baker cloud api): rebuild without (remove) eaccelerator

**Comment by nin9creative** [comment]
Closing due to age of issue.  Please reopen if still required.
