### ISSUE TITLE
Invalid receipts & number of purchases incorrect

### ISSUE THREAD

**Issue by philahern** [bakerframework/bakercloud-ce-console#42]
I have a magazine live in the app store for a week now. I am getting a couple of reports of people not getting their in-app purchases validated. Apple says that the purchase has been made but they still see the price (no download option) Looking on the baker cloud app I can see that there are invalid receipts appearing in the log:

e.g. Invalid receipt for APP ID: *****\* USER ID: ****\* STATUS: 21002

Looking at the stats on iTunes Connect it says I have 4 more purchases than recorded in Baker Cloud. 

Does anyone know what the problem might be?

**Comment by philahern** [comment]
I seem to have 4 receipts in the RECEIPTS table that have no data except for APP_ID and USER_ID. I am also getting records in the PURCHASES table that have a blank PRODUCT_ID. It seems like there is a call to the api but there is no POST data in the call?

**Comment by reefmag** [comment]
I seem to be having the same issue "Invalid receipt for APP ID" and blank product_ID were you able to rectify this?

**Comment by nin9creative** [comment]
Are you using the release version or the github repo latest?

Andrew

**Comment by reefmag** [comment]
I am using the version from - http://www.bakerframework.com/bakercloudce/ 
If I understand your questions correctly.

**Comment by nin9creative** [comment]
Have you checked for error messages or other logged messages in the SYSTEM LOG table?

**Comment by reefmag** [comment]
This is the latest in the System Log 
Warning     Invalid receipt for APP ID: xxxx USER ID: xxxxx  STATUS: 21002 

Also on the Receipts management page, there are 2 User IDs  with blank product IDs and blank purchase dates.

**Comment by reefmag** [comment]
I just got another one of these in the System Log table- 
"Warning    Invalid receipt for APP ID: xxxx USER ID: xxxxx STATUS: 21002 "
Is it that users aren't able to receive or read the magazine issue?

Does anyone know how to fix this?

**Comment by nin9creative** [comment]
Closing due to age of issue.  Please reopen if still required.
