### ISSUE TITLE
Defining product IDs for issues

### ISSUE THREAD

**Issue by lyndonl** [bakerframework/bakercloud-ce-console#43]
I'm managing my issues using the Bakercloud console and even though I can subscribe to an issue in the sandbox environment, download it and read it without problems on my iPad, I am getting an "Invalid product identifier" error in Xcode:

Invalid product identifier: com.company.magazine.subscriptions.september2014

Where the last two parameters of the identifier above are ones I came up with along the lines of the naming convention of the BakerMagazine example. (I've also substituted my actual company and magazine names for presentation here.)

I see from the BakerMagazine demo that the January issue, for example, has a productID of com.nin9creative.baker.issues.january2013

Where is that referenced or defined elsewhere, though? I assumed that because we were managing issues through Publication Management in the Bakercloud console that we don't need to define individual issues in iTunesConnect. Or am I mistaken?

Like I say, even though I'm getting the error in Xcode, the issue is delivered without problems to my divide using the hpub destination settings I defined in the Bakercloud console.

Any ideas, anyone?

In the interests of providing full detail, I have a free, non-consumerable item set up for the magazine container and then a monthly auto-subscription IAP with the identifier:

com.company.magazine.subscriptions.monthly

Thanks in advance.

**Comment by nin9creative** [comment]
You still need non consumable in app purchases defined in iTunes Connect
for each of the issues you want to charge.

On Fri, Oct 3, 2014 at 3:57 PM, lyndonl notifications@github.com wrote:

> I'm managing my issues using the Bakercloud console and even though I can
> subscribe to an issue in the sandbox environment, download it and read it
> without problems on my iPad, I am getting an "Invalid product identifier"
> error in Xcode:
> 
> Invalid product identifier:
> com.company.magazine.subscriptions.september2014
> 
> Where the last two parameters of the identifier above are ones I came up
> with along the lines of the naming convention of the BakerMagazine example.
> (I've also substituted my actual company and magazine names for
> presentation here.)
> 
> I see from the BakerMagazine demo that the January issue, for example, has
> a productID of com.nin9creative.baker.issues.january2013
> 
> Where is that referenced or defined elsewhere, though? I assumed that
> because we were managing issues through Publication Management in the
> Bakercloud console that we don't need to define individual issues in
> iTunesConnect. Or am I mistaken?
> 
> Like I say, even though I'm getting the error in Xcode, the issue is
> delivered without problems to my divide using the hpub destination settings
> I defined in the Bakercloud console.
> 
> Any ideas, anyone?
> 
> In the interests of providing full detail, I have a free, non-consumerable
> item set up for the magazine container and then a monthly auto-subscription
> IAP with the identifier:
> 
> com.company.magazine.subscriptions.monthly
> 
> Thanks in advance.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bakerframework/bakercloud-ce-console/issues/43.

## 

John Andrews Photography
877-805-1983 Toll-free
888-536-0183 Secure Fax
630-247-1171 Cell
www.johnandrewsphotography.com
blog.johnandrewsphotography.com

**Comment by lyndonl** [comment]
Thanks, Andrew.

Do I price that at the subscription rate, then, or free like the shell non-consumerable app?
