### ISSUE TITLE
Cannot get APNS Token when a user subscribes.

### ISSUE THREAD

**Issue by jdurhamrtm** [bakerframework/bakercloud-ce-console#46]
I am testing my free subscriptions, and when I subscribe I am not getting an APNS so I can send push notifications.

**Comment by nin9creative** [comment]
It should happen the first time the app is launched and the register for push notifications prompt comes up.

At that point, if you have the API endpoint set correctly it will post the token value to the backend.

**Comment by jdurhamrtm** [comment]
I followed the directions on how to set everything up. So I believe everything is correct. Should I delete my Baker Cloud Console and reset it up and see if it works?

**Comment by nin9creative** [comment]
What is the URL you have setup in the Constants.h file for the TOKEN url?

**Comment by jdurhamrtm** [comment]
http://api.realtruthmatters.com/apns/:app_id/:user_id

**Comment by jdurhamrtm** [comment]
I noticed I am getting this in a window when I run my app:

registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.

**Comment by jdurhamrtm** [comment]
Anyone have any ideas?

**Comment by fcontreras** [comment]
From what I saw on iOS8 registerForRemoteNotificationTypes is not supported anymore and we need to use registerUserNotificationSettings. Baker iOS code may need some love.

**Comment by jdurhamrtm** [comment]
Ok, thanks for the response. Any idea on a time frame where this will be fixed?
