### ISSUE TITLE
IPAD Landscape sizing issue

### ISSUE THREAD

**Issue by masood11** [bakerframework/bakercloud-ce-console#47]
Im developing newstand for ipad, downloaded baker 4.2.1.It worked fine in IOS7, xcode5.  But getting
orientation issues in xcode6.1 sdk ios8.1

**Comment by nin9creative** [comment]
This might be better suited for the main Baker Issue list.

https://github.com/bakerframework/baker/issues

**Comment by masood11** [comment]
Have a look
https://github.com/bakerframework/baker/issues/367

On 11/12/2014 8:03 PM, Andrew wrote:

> This might be better suited for the main Baker Issue list.
> 
> https://github.com/bakerframework/baker/issues
> 
> ---
> 
> From: masood11 notifications@github.com
> To: bakerframework/bakercloud-ce-console 
> bakercloud-ce-console@noreply.github.com
> Sent: Wednesday, November 12, 2014 9:43 AM
> Subject: [bakercloud-ce-console] IPAD Landscape sizing issue (#47)
> 
> Im developing newstand for ipad, downloaded baker 4.2.1.It worked fine 
> in IOS& xcode5, But getting
> orientation issues in xcode6.1 sdk ios8.1
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bakerframework/bakercloud-ce-console/issues/47#issuecomment-62752962.

## 

Index
Mohammad Masood
Web Designer

[be committed] <#>  [seek development] <#>  [stay positive] <#>     [grow 
with us] <#>

M +966 532 145 317|T +966 11279 2043    Connect with us
F +966 11288 6447|P.O.Box 250704 Riyadh 11391 |KSA  
https://www.facebook.com/Brainstormin.communications 
https://twitter.com/Brainstormin_     http://vimeo.com/user8796129 
http://www.youtube.com/channel/UCw67QigWQB3895ZMqbP1etQ/feed 
https://plus.google.com/118206144011933306053 
https://www.behance.net/braindingsa 
http://www.linkedin.com/company/braindingarabia

http://thebrainstorming.com/  http://www.brainding.com/ 
http://www.brainstormingadvertising.com/  http://brainimation.com/

**Comment by salihaksu** [comment]
Hi, i'm having same problem. I looked up for thoese issues download new files from Baker,  but i think this files are not compatable with Baker Cloud xCode project?

**Comment by nin9creative** [comment]
Closing due to age of issue.  Please reopen if still required.
