### ISSUE TITLE
stuck - cant subscribe

### ISSUE THREAD

**Issue by axilaris** [bakerframework/bakercloud-ce-console#5]
Is there something we should do to make subscription work ? I'ved already put in the product ids in AUTO_RENEWABLE_SUBSCRIPTION_PRODUCT_IDS. But even after I have purchased the subscription, i dont notice anything.

It still says "You are not subscribed". I dont even see the paid products being free, i still need to pay separately.

Im still getting json string, as you can see, subscribed is false.
{"issues":["com.nin9creative.magrocket.issues.january2013"],"subscribed":false}
 how can i make sure when a purchase is done, the backend get updated the subscription ?

Thanks

**Comment by axilaris** [comment]
Im not sure if this is even right, that even its not subscribed, it shows success. something is not right.
How do you make subscription work with baker ?

ShelfViewController.m
- (void)handleSubscriptionPurchased:(NSNotification *)notification {
  SKPaymentTransaction *transaction = [notification.userInfo objectForKey:@"transaction"];
  
  [purchasesManager markAsPurchased:transaction.payment.productIdentifier];
  [self setSubscribeButtonEnabled:YES];
  
  if ([purchasesManager finishTransaction:transaction]) {
      if (!purchasesManager.subscribed) {
          [Utils showAlertWithTitle:NSLocalizedString(@"SUBSCRIPTION_SUCCESSFUL_TITLE", nil)
                            message:NSLocalizedString(@"SUBSCRIPTION_SUCCESSFUL_MESSAGE", nil)
                        buttonTitle:NSLocalizedString(@"SUBSCRIPTION_SUCCESSFUL_CLOSE", nil)];
  
  ```
      [self handleRefresh:nil];
  }
  ```

**Comment by axilaris** [comment]
not sure if this helps, here are some logs I found:
1798     Warning     Invalid receipt for APP ID: com.nin9creative.magrocket USER ID: user PRODUCT ID: STATUS: 21007  2013-12-08 13:43:31
1799     Error   Invalid Receipt

i wonder if i should create a new publication then the default com.nin9creative.magrocket which i dont own that app id

**Comment by nin9creative** [comment]
What are you trying to purchase?

If you are testing your own application then it shouldn't have anything related to nin9creative/magrocket as an App ID.

If you are trying to test with data that comes out of the box for demonstration purposes - it won't work for full cycle subscription testing.

You need to use your own publication / app details.

Andrew

**Comment by nin9creative** [comment]
There is no Baker example where you can test because the purchase of the subscriptions are based on your iTunes Connect test ID setups.

It needs to be setup and associated with your application / itunes / baker etc...

Without some more details on how you have everything setup, I don't know what might be going wrong.

**Comment by nin9creative** [comment]
Did this ever get resolved?

**Comment by nin9creative** [comment]
Closing this.  If you still are having issues, please re-open.
