### ISSUE TITLE
Compatibility issues with PHP 5.6

### ISSUE THREAD

**Issue by ReqM** [bakerframework/bakercloud-ce-console#55]
I've been using the console with PHP 5.3 all this time without issues, my hosting is updating the servers to PHP 5.6 so I tested it with baker cloud and got the following before log in:
![screen shot 2016-03-01 at 12 57 55 pm](https://cloud.githubusercontent.com/assets/17575666/13438168/75d668d6-dfad-11e5-9bd9-e9dcd302e640.png)
And the following after login:
![screen shot 2016-03-01 at 12 58 40 pm](https://cloud.githubusercontent.com/assets/17575666/13438182/862d9862-dfad-11e5-8338-14239154db53.png)
@nin9creative Will you by any chance make an upgrade to make it compatible with PHP 5.6?

**Comment by nin9creative** [comment]
Would need to take a look, but most likely it's releated to the CodeIgniter underlying framework.  Might want to search for CodeIgniter and these error messages on Google for the short term.

```
  From: ReqM <notifications@github.com>
```

 To: bakerframework/bakercloud-ce-console bakercloud-ce-console@noreply.github.com 
Cc: Andrew andrew@nin9creative.com
 Sent: Tuesday, March 1, 2016 1:06 PM
 Subject: [bakercloud-ce-console] Compatibility issues with PHP 5.6 (#55)

I've been using the console with PHP 5.3 all this time without issues, my hosting is updating the servers to PHP 5.6 so I tested it with baker cloud and got the following before log in:

And the following after login:

@nin9creative Will you by any chance make an upgrade to make it compatible with PHP 5.6?—

**Comment by ReqM** [comment]
Hi, I tried to fix the codeingniter issues but I still have some problems. Do you have any news in this topic?

**Comment by Manbur** [comment]
I have the same problem with  PHP 5.6 and PHP 7, any solution?

**Comment by drhounsell** [comment]
Anyone solve getting Baker Cloud to work with PHP 5.6?

**Comment by riotxoa** [comment]
To solve "Only variable references should be returned by reference" in core/Common.php line 257 you must edit that file and replace this line:

`return $_config[0] =& $config;`

By these new ones:

`$_config[0] =& $config;`
`return $_config[0];`
