### ISSUE TITLE
stuck on "updating price"

### ISSUE THREAD

**Issue by 42south** [bakerframework/bakercloud-ce-console#6]
Everything is working perfectly. Server set up, Xcode building without any problems. Simulator opening. My single issue is appearing in the simulator, but then I get an endless spinning wheel and "updating price". I've checked iTunes and the price is set at "tier 3" and "cleared for sale". The "subscribe' drop-down says "you are not subscribed" and "Restore purchases". It doesn't show my two subscription options. Maybe it's something to do with sandbox. Do I have to do anything on iTunes to set up sandbox, or does baker do that automatically?

**Comment by nin9creative** [comment]
You have the subscriptions defined in the Constants.h?  And the single Non Consumable Purchase product ID assigned to the issue in the server?  (check for trailing and leading spaces).

Andrew

**Comment by 42south** [comment]
Yes to both. Should the issue availability be set to "pending" or "published". I had it set to pending, but the issue didn't show up in the simulator. When I set it to "published' it showed up, but with the "updating price" problem. It looks to me as if the simulator is looking for an issue in the iTunes store, rather than sandbox??

**Comment by nin9creative** [comment]
Currently it needs to be published to see it in the simulator.  At some point I was going to add an enhancement to return
pending issues when the mode of the application (Baker) was sent across as debug - but haven't gotten around to that yet.
The info was just added in the Baker 4.2 release (notifying backend of debug/production).

If you are sure everything is correct, sometimes I've noticed that the updating price thing takes some time to start working on the iTunes side.

**Comment by 42south** [comment]
OK. I'll keep monitoring progress and report back. Thanks for all your hard work, Andrew. You have saved me so much time, not to mention money! As soon as I get my first issue up on Newsstand I'll make a donation. Cheers.

**Comment by 42south** [comment]
I'm a bit lost here. I still get stuck on "updating price" in the simulator. I connected my iPad and ran the app there and the price came up OK, as did the subscription details in the drop-down. However, when I try to buy or subscribe I get the error "cannot connect to iTunes store". It looks as though the sandbox environment isn't working. I notice there is no sandbox in the Xcode capabilities. Is this how it should be? Is there something I need to do to activate the sandbox?

**Comment by nin9creative** [comment]
From 7.0 onward the sandbox doesn't work in the simulator.  You'll need to test on the device.  Sorry if I didn't mention that prior...

Regards,
Andrew

**Comment by 42south** [comment]
Yes, but the sandbox isn't working on the device either. I just get the error "cannot connect to iTunes store"

**Comment by nin9creative** [comment]
Email me the Constants.h and a screenshot of your Baker project settings...  Also if you can screenshot the iTunes connect setup and send me the login to the cloud console I'll take a look...

Regards,
Andrew

**Comment by 42south** [comment]
OK. I'll send those through in a couple of minutes.

**Comment by 42south** [comment]
cloud console login: user: user password: solar2013

![constants h](https://f.cloud.github.com/assets/6058915/1710880/2eac00c8-613e-11e3-86d5-90130285a145.png)
![itunes 2](https://f.cloud.github.com/assets/6058915/1710882/3751bd30-613e-11e3-90b4-75d803574a5a.png)
![itunes 1](https://f.cloud.github.com/assets/6058915/1710883/38a8c390-613e-11e3-9607-954684cef22a.png)
![xcode settings](https://f.cloud.github.com/assets/6058915/1710884/38adb76a-613e-11e3-899c-9afa1e22efe4.png)

**Comment by 42south** [comment]
sorry, url: app.42southmags.com

**Comment by nin9creative** [comment]
You might not want to post the login info publically :)

However I don't see anything wrong.   You are testing with a Sandbox ID that you created in iTunes Connect?

Andrew

**Comment by 42south** [comment]
I'll change the password when we're finished. How do you create a sandbox ID in iTunes? I'm just using my normal ID.

**Comment by nin9creative** [comment]
On the main dashboard page when you log into iTunes Connect there is an icon called "Manage Users"

Click that then select "Test User"

You can create a user that will be valid against the Sandbox environment.

Andrew

**Comment by 42south** [comment]
Yes, I already had a test user set up, but I don't get to the point of being able to use it, because when I try to buy from the iPad I just get the error message (can't connect to iTunes Store). I don't get to choose a user the way it works in your installation video. The dialogue which indicates "environment sandbox" doesn't show up. The dialogue reads; "purchase failure. Cannot connect to iTunes Store." The only option shown is "close". So I'm stuck again.

**Comment by nin9creative** [comment]
Can you try going to your Settings on your iPad and logging out the user for the App Store?

**Comment by 42south** [comment]
Eureka! That solved the problem. After logging out on the App Store I got the sandbox dialogue, was able to log in with the test user ID and buy the issue. Many thanks Andrew, it looks like magrocket is fully functional, and I can move on to the next phase. 

Regards
Rex

**Comment by nin9creative** [comment]
Ok great!
