### ISSUE TITLE
Free issues not beeing logged?

### ISSUE THREAD

**Issue by bingimar** [bakerframework/bakercloud-ce-console#8]
Wanted to know if free issues were not beeing logged like in the MagRocket version?

**Comment by nin9creative** [comment]
I still don't know exactly what you are referring to...

**Comment by bingimar** [comment]
All free issues are not beeing logged in MagRocket when users download them. I see the download and the request in the apache logs but not in MagRocket.

**Comment by nin9creative** [comment]
If you don't have the Issue Security bit turned on, the request never comes back to MagRocket in order for it to know that an issue is being downloaded.

When it's off, the API sends back the normal URL to the Hpub which Baker then directly calls for the download.  When it's on, the API returns a URL back
to the API itself, which then logs the message and redirects to the actual endpoint URL for the download.

**Comment by bingimar** [comment]
Ok tried turning it on and I'm getting a 403 error on those issues.

46.239.214.177 - - [12/Dec/2013:22:16:59 +0000] "HEAD /issue/com.nordicstylemag.magazine/[USER_ID]/issue4?user_id=[USER_ID]&app_id=com.nordicstylemag.magazine&environment=production HTTP/1.1" 403 280 "-" "itunesstored/1.0 iOS/7.0.4 model/iPad2,6 (5; dt:87)"

nb. removed actual user id

**Comment by nin9creative** [comment]
Can you look at Issue #7 ?  Seems to be similar issue.

**Comment by bingimar** [comment]
Resolved in issue #7
