### ISSUE TITLE
Integration with Gindpubs

### ISSUE THREAD

**Issue by jtrader** [bakerframework/bakercloud-ce-console#9]
Just wondering if there are plans to integrate bakercloud console with android apps via Gindpubs(https://github.com/fcontreras/gindpubs-frameworks)?

**Comment by nin9creative** [comment]
I've chatted with @fcontreras before about Baker stuff...  Right now I'm not sure...

This is one thing that I've pondered for a bit, whether or not we should push for an "official" Android framework.

**Comment by MaverickWar** [comment]
It sure would be nice though to see baker expand to cover other platforms. Appreciate you want to really build it's original Apple offering but the reality is now that many users that always had only Apple products now use google/kindle/windows devices. Especially Google with the nexus lines on tablet and phone.. Just my 2 cents. Apple should still be the main goal I think but I don't think it would hurt to build the other versions also.

**Comment by fobetor** [comment]
Yes, it would be a great advance

**Comment by nin9creative** [comment]
Closing this for now.  Stay tuned for some announcements regarding this topic relatively soon.
